### ISSUE TITLE
Migrate from HCL to config lang that supports comments and optional attribute

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace#48]
Previous iteration of `gitspace` tried JSON which was easy to implement, but a pain to maintain.

Migrated to HCL because I enjoy using it when working with Terraform. 
Lightweight compared to JSON and easier to format & read compared to YAML. 

However, after the emphasis on JSON interop (which is a good thing) has led Hashi to lead in direction of not supporting optionality for fields which isn't great. Think that TOML will strike a better balance for us.

Start by converting this into something usable in TOML:
```hcl
gitspace {
  path = "gs"
  labels = ["feature", "bug"]
  clone {
    scm = "github.com"
    owner = "ssotops"
    auth {
      type = "ssh"
      keyPath = "$SSH_KEY_PATH"
    }

    startsWith {
      group "git" {
        values = ["git"]
          type = "gitops"
          labels = ["backend", "core"]
      }
    }

    endsWith {
      group "space" {
        values = ["space"]
        type = "solution"
        labels = ["frontend", "experimental"]
      } 
    }

    includes {
      group "sso" {
        values = ["sso"]
        type = "ssot"
        labels = ["auth", "security"]
      }
      group "plugins" {
        values = ["-plugin-"]
      }
      group "templates" {
        values = ["-template-"]
      }
    }

    isExactly { // Changed from name to isExactly
      group "scmany" {
        values = ["scmany"]
        type = "helper"
        labels = ["utility"]
      }
    }
  }
}
```

**Comment by alechp** [comment]
Lowkey this looks like garbage though :/
```toml
[gitspace]
path = "gs"
labels = ["feature", "bug"]

[gitspace.clone]
scm = "github.com"
owner = "ssotops"

[gitspace.clone.auth]
type = "ssh"
keyPath = "$SSH_KEY_PATH"

[gitspace.clone.startsWith.group.git]
values = ["git"]
type = "gitops"
labels = ["backend", "core"]

[gitspace.clone.endsWith.group.space]
values = ["space"]
type = "solution"
labels = ["frontend", "experimental"]

[gitspace.clone.includes.group.sso]
values = ["sso"]
type = "ssot"
labels = ["auth", "security"]

[gitspace.clone.includes.group.plugins]
values = ["-plugin-"]

[gitspace.clone.includes.group.templates]
values = ["-template-"]

[gitspace.clone.isExactly.group.scmany]
values = ["scmany"]
type = "helper"
labels = ["utility"]
```
