### ISSUE TITLE
Enable users to install from local or remote sources

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace#51]
## Preparation
1) Leave it in the examples repo so we can test local installs
2) Create a new private Github repository in ssotops so we can test it (github.com/ssotops/gitspace-plugin-hello-hello-galaxy)
3) Create a new public Github repository in ssotops so we can test it (github.com/ssotops/gitspace-plugin-hello-universe)

## Plugin Improvements 
Current plugin sub-menu looks like this
<img width="416" alt="Screenshot 2024-09-08 at 3 56 24 PM" src="https://github.com/user-attachments/assets/e1d90bdf-456f-4729-ab9d-177146a7dede">

If we click `Install Plugin` it immediately jumps to what would be the "local" option. We have a little `path_completion.go` file which semi-simulates terminal tabbing. 
<img width="955" alt="Screenshot 2024-09-08 at 3 56 43 PM" src="https://github.com/user-attachments/assets/f1ec98ed-f928-4b21-af7b-ab643726110a">

While we may want to eventually support a "registry" of repositories, it'll be easier for the moment to just leave that to the plugin manifest and allow it to specify.

**Comment by alechp** [comment]
For now using this as the TOML hello world example:
```toml
[plugin]
name = "hello_world"
version = "1.0.0"
description = "A simple Hello World plugin for Gitspace"
author = "Gitspace Team"

[[plugin.sources]]
path = "hello_world"
entry_point = "Plugin"

# [plugin.sources.repository]
# type = "github"
# url = "https://github.com/ssotops/gitspace-hello-world-plugin"
# branch = "master"

# You can add more plugin sources like this:
# [[plugin.sources]]
# path = "another_plugin"
# entry_point = "AnotherPlugin"
# 
# [plugin.sources.repository]
# type = "gitlab"
# url = "https://gitlab.com/ssotops/another-gitspace-plugin"
# branch = "main"
```
