### ISSUE TITLE
Allow users to overwrite the default `scm` and `owner` specified globally

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace#52]
Example:
```toml
[global]
path = "gs"
labels = ["feature", "bug"]
scm = "github.com"
owner = "ssotops"

[auth]
type = "ssh"
key_path = "$SSH_KEY_PATH"

[groups.plugins]
match = "includes"
values = ["plugin", "template"]

type = "helper"
[groups.git]
match = "startsWith"
values = ["git"]
type = "gitops"
labels = ["backend", "core"]

[groups.space]
match = "endsWith"
values = ["space"]
type = "solution"
labels = ["frontend", "experimental"]

[groups.sso]
match = "includes"
values = ["sso"]
type = "ssot"
labels = ["auth", "security"]

[groups.scmany]
match = "isExactly"
values = ["scmany"]
type = "helper"
labels = ["utility"]
```

Example use case would be if you have an SSOT repository in a distinct org then you might want to change this to include scm and owner:
```toml
[groups.sso]
scm = "gitlab" # instead of github like in global
owner = "ssotops-test" # instead of ssotops like in global
match = "includes"
values = ["sso"]
type = "ssot"
labels = ["auth", "security"]
```
