### ISSUE TITLE
Migrate `labels` from core to a plugin

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace#61]
Couple things I don't like, using this config as an example:
```toml
[global]
path = "gs"
labels = ["feature", "bug"]
scm = "github.com"
owner = "ssotops"

[auth]
type = "ssh"
key_path = "$SSH_KEY_PATH"

[groups.plugins-and-templates]
match = "includes"
values = ["plugin", "template"]
type = "helper"

[groups.git]
match = "startsWith"
values = ["git"]
type = "gitops"
labels = ["backend", "core"]

[groups.space]
match = "endsWith"
values = ["space"]
type = "solution"
labels = ["frontend", "experimental"]

[groups.sso]
match = "includes"
values = ["sso"]
type = "ssot"
labels = ["auth", "security"]

[groups.scmany]
match = "isExactly"
values = ["scmany"]
type = "helper"
labels = ["utility"]
```

The order of precedence on labels is confusing. Example: with workspaces, we can simply assume M:1 symlink:repo. With labels, it makes sense to assume the same. But then there's a question: say we're using the `gitops` type specifically for `startsWith("git")` and have `gitspace-plugin-hello-universe`... This is now marked as a `gitops` type repo. 

## Action items
1. Migrate labels from core to plugin
2. Add a k/v pair that allows specifying the order of precedence & attribute exclusions for each repository
