### ISSUE TITLE
Make `match` on multiple directives possible

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace#63]
In anticipation of resolving #62 , as I look at this config:
```toml
[global]
path = "gs"
labels = ["feature", "bug"]
scm = "github.com"
owner = "ssotops"

[auth]
type = "ssh"
key_path = "$SSH_KEY_PATH"

[groups.git]
match = "startsWith"
values = ["git"]
type = "gitops"
labels = ["backend", "core"]

[groups.space]
match = "endsWith"
values = ["space"]
type = "solution"
labels = ["frontend", "experimental"]

[groups.sso]
match = "includes"
values = ["sso"]
type = "ssot"
labels = ["auth", "security"]

[groups.scmany]
match = "isExactly"
values = ["scmany"]
type = "helper"
labels = ["utility"]
```

Realizing that it would be more helpful to be able to specify multiple `match:value` pairings. Right now, the relationship is one match directive (eg. `includes`, `endsWith`, etc.) with multiple values. This is convenient and powerful until we try to solve for types, labels, and other attribution.

Imagine isntead:
```
[ 
type = "gitspace extension"
match = { startsWith="git" }, {includes=["plugin", "template"]}
]
```

In this example, `gitspace` and `gitspace-catalog` would be excluded, but `gitspace-plugin-hello-galaxy` and `gitspace-plugin-hello-universe` would both be included and tagged appropriately. 
<img width="862" alt="Screenshot 2024-09-09 at 3 23 33 PM" src="https://github.com/user-attachments/assets/b419b511-5cd5-4160-a222-fff80ace79af">
