### ISSUE TITLE
Clean up `gitspace-plugin.toml` manifest management

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace#92]
This impacts both `gitspace` and `gitspace-catalog`

1. Ensure that all plugin parsing is in a lib accessible to both gs & catalog
2. Rename `[metadata]` to `[plugin]` 
```toml
[metadata]
name = "scmtea"
version = "1.0.0"
description = "A plugin for managing Gitea in Docker"

[[sources]]
path = "main.go"
entry_point = "ScmteaPlugin"
```
3. Remove current `entry_point`
4. Rename `path` in sources to `entry_point`
5. Update relevant manifests
6. Change from `[[sources]]` to `[source]`
